# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_compotte.ui'
#
# Created: Sat Apr 26 19:13:05 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Compotte(object):
    def setupUi(self, Compotte):
        Compotte.setObjectName(_fromUtf8("Compotte"))
        Compotte.resize(526, 563)
        self.mainScrollArea = QtGui.QScrollArea(Compotte)
        self.mainScrollArea.setGeometry(QtCore.QRect(0, 0, 521, 551))
        self.mainScrollArea.setWidgetResizable(True)
        self.mainScrollArea.setObjectName(_fromUtf8("mainScrollArea"))
        self.mainScrollAreaWidgetContents = QtGui.QWidget()
        self.mainScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 519, 549))
        self.mainScrollAreaWidgetContents.setObjectName(_fromUtf8("mainScrollAreaWidgetContents"))
        self.lblOnlineResource = QtGui.QLabel(self.mainScrollAreaWidgetContents)
        self.lblOnlineResource.setGeometry(QtCore.QRect(10, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblOnlineResource.setFont(font)
        self.lblOnlineResource.setObjectName(_fromUtf8("lblOnlineResource"))
        self.cmdNew = QtGui.QPushButton(self.mainScrollAreaWidgetContents)
        self.cmdNew.setGeometry(QtCore.QRect(10, 80, 71, 27))
        self.cmdNew.setObjectName(_fromUtf8("cmdNew"))
        self.frmMain = QtGui.QFrame(self.mainScrollAreaWidgetContents)
        self.frmMain.setGeometry(QtCore.QRect(10, 120, 501, 421))
        self.frmMain.setAutoFillBackground(False)
        self.frmMain.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmMain.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMain.setObjectName(_fromUtf8("frmMain"))
        self.lblMessage = QtGui.QLabel(self.frmMain)
        self.lblMessage.setGeometry(QtCore.QRect(10, 390, 481, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblMessage.setFont(font)
        self.lblMessage.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblMessage.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblMessage.setText(_fromUtf8(""))
        self.lblMessage.setObjectName(_fromUtf8("lblMessage"))
        self.lblInfo = QtGui.QLabel(self.frmMain)
        self.lblInfo.setGeometry(QtCore.QRect(10, 50, 481, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblInfo.setFont(font)
        self.lblInfo.setObjectName(_fromUtf8("lblInfo"))
        self.tabWidget = QtGui.QTabWidget(self.frmMain)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 501, 381))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.cmbStyle = QtGui.QComboBox(self.tab)
        self.cmbStyle.setGeometry(QtCore.QRect(0, 120, 481, 22))
        self.cmbStyle.setObjectName(_fromUtf8("cmbStyle"))
        self.cmdGetFeature = QtGui.QPushButton(self.tab)
        self.cmdGetFeature.setEnabled(False)
        self.cmdGetFeature.setGeometry(QtCore.QRect(10, 320, 111, 23))
        self.cmdGetFeature.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmdGetFeature.setObjectName(_fromUtf8("cmdGetFeature"))
        self.cmbFeatureType = QtGui.QComboBox(self.tab)
        self.cmbFeatureType.setGeometry(QtCore.QRect(0, 70, 481, 22))
        self.cmbFeatureType.setObjectName(_fromUtf8("cmbFeatureType"))
        self.lblFeature = QtGui.QLabel(self.tab)
        self.lblFeature.setGeometry(QtCore.QRect(0, 50, 481, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblFeature.setFont(font)
        self.lblFeature.setObjectName(_fromUtf8("lblFeature"))
        self.cmdGetCapabilities = QtGui.QPushButton(self.tab)
        self.cmdGetCapabilities.setGeometry(QtCore.QRect(0, 10, 131, 23))
        self.cmdGetCapabilities.setObjectName(_fromUtf8("cmdGetCapabilities"))
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(130, 320, 361, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.lblStyle = QtGui.QLabel(self.tab)
        self.lblStyle.setGeometry(QtCore.QRect(0, 100, 481, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblStyle.setFont(font)
        self.lblStyle.setObjectName(_fromUtf8("lblStyle"))
        self.txtFeatureTypeTitle = QtGui.QPlainTextEdit(self.tab)
        self.txtFeatureTypeTitle.setGeometry(QtCore.QRect(0, 150, 481, 31))
        self.txtFeatureTypeTitle.setReadOnly(True)
        self.txtFeatureTypeTitle.setObjectName(_fromUtf8("txtFeatureTypeTitle"))
        self.txtFeatureTypeDescription = QtGui.QPlainTextEdit(self.tab)
        self.txtFeatureTypeDescription.setGeometry(QtCore.QRect(0, 190, 481, 91))
        self.txtFeatureTypeDescription.setReadOnly(True)
        self.txtFeatureTypeDescription.setObjectName(_fromUtf8("txtFeatureTypeDescription"))
        self.lblSrs = QtGui.QLabel(self.tab)
        self.lblSrs.setGeometry(QtCore.QRect(10, 290, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblSrs.setFont(font)
        self.lblSrs.setObjectName(_fromUtf8("lblSrs"))
        self.txtSrs = QtGui.QLineEdit(self.tab)
        self.txtSrs.setGeometry(QtCore.QRect(40, 290, 131, 20))
        self.txtSrs.setText(_fromUtf8(""))
        self.txtSrs.setObjectName(_fromUtf8("txtSrs"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.cmdAddComposition = QtGui.QPushButton(self.tab_2)
        self.cmdAddComposition.setEnabled(False)
        self.cmdAddComposition.setGeometry(QtCore.QRect(160, 320, 181, 27))
        self.cmdAddComposition.setObjectName(_fromUtf8("cmdAddComposition"))
        self.compositionURL = QtGui.QLineEdit(self.tab_2)
        self.compositionURL.setGeometry(QtCore.QRect(10, 30, 451, 21))
        self.compositionURL.setText(_fromUtf8(""))
        self.compositionURL.setObjectName(_fromUtf8("compositionURL"))
        self.cmdBrowseComposition = QtGui.QPushButton(self.tab_2)
        self.cmdBrowseComposition.setGeometry(QtCore.QRect(437, 100, 41, 21))
        self.cmdBrowseComposition.setObjectName(_fromUtf8("cmdBrowseComposition"))
        self.filePath = QtGui.QLineEdit(self.tab_2)
        self.filePath.setGeometry(QtCore.QRect(10, 100, 421, 21))
        self.filePath.setReadOnly(True)
        self.filePath.setObjectName(_fromUtf8("filePath"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(150, 60, 66, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 151, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cmdCheckComposition = QtGui.QPushButton(self.tab_2)
        self.cmdCheckComposition.setGeometry(QtCore.QRect(10, 320, 141, 27))
        self.cmdCheckComposition.setObjectName(_fromUtf8("cmdCheckComposition"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 471, 181))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.cmdCancel = QtGui.QPushButton(self.tab_2)
        self.cmdCancel.setEnabled(False)
        self.cmdCancel.setGeometry(QtCore.QRect(350, 320, 131, 27))
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.lblMain = QtGui.QLabel(self.mainScrollAreaWidgetContents)
        self.lblMain.setGeometry(QtCore.QRect(10, 20, 321, 31))
        self.lblMain.setObjectName(_fromUtf8("lblMain"))
        self.cmbService = QtGui.QComboBox(self.mainScrollAreaWidgetContents)
        self.cmbService.setGeometry(QtCore.QRect(10, 50, 481, 27))
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.cmdEdit = QtGui.QPushButton(self.mainScrollAreaWidgetContents)
        self.cmdEdit.setGeometry(QtCore.QRect(90, 80, 71, 27))
        self.cmdEdit.setObjectName(_fromUtf8("cmdEdit"))
        self.cmdDelete = QtGui.QPushButton(self.mainScrollAreaWidgetContents)
        self.cmdDelete.setGeometry(QtCore.QRect(170, 80, 71, 27))
        self.cmdDelete.setObjectName(_fromUtf8("cmdDelete"))
        self.mainScrollArea.setWidget(self.mainScrollAreaWidgetContents)

        self.retranslateUi(Compotte)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Compotte)

    def retranslateUi(self, Compotte):
        Compotte.setWindowTitle(_translate("Compotte", "Compotte", None))
        self.lblOnlineResource.setText(_translate("Compotte", "Resource URL", None))
        self.cmdNew.setText(_translate("Compotte", "New", None))
        self.lblInfo.setText(_translate("Compotte", "Feature", None))
        self.cmdGetFeature.setText(_translate("Compotte", "GetFeature(s)", None))
        self.lblFeature.setText(_translate("Compotte", "Feature", None))
        self.cmdGetCapabilities.setText(_translate("Compotte", "GetCapabilities", None))
        self.lblStyle.setText(_translate("Compotte", "Style", None))
        self.lblSrs.setText(_translate("Compotte", "SRS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Compotte", "Layer", None))
        self.cmdAddComposition.setText(_translate("Compotte", "Download composition", None))
        self.cmdBrowseComposition.setText(_translate("Compotte", "...", None))
        self.label_2.setText(_translate("Compotte", "OR", None))
        self.label_3.setText(_translate("Compotte", "Composition URL", None))
        self.label_4.setText(_translate("Compotte", "Composition file path", None))
        self.cmdCheckComposition.setText(_translate("Compotte", "Check composition", None))
        self.cmdCancel.setText(_translate("Compotte", "Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Compotte", "Composition", None))
        self.lblMain.setText(_translate("Compotte", "Compottable portal", None))
        self.cmdEdit.setText(_translate("Compotte", "Edit", None))
        self.cmdDelete.setText(_translate("Compotte", "Delete", None))

